image: ghcr.io/cirruslabs/flutter:3.24.1

stages:
  - build
  - test

before_script:
  # Cache-Verzeichnis definieren
  - flutter config --enable-web
  - flutter pub get

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .pub-cache/
    - build/

build:
  stage: build
  script:
    - flutter build web --web-renderer canvaskit --release --no-tree-shake-icons
  rules:
    - when: always
  artifacts:
    paths:
     - build/web/

test:
  stage: test
  script:
    - flutter test --coverage
  rules:
    - when: always
  artifacts:
    paths:
      - coverage/lcov.info