image: ghcr.io/cirruslabs/flutter:3.24.1

stages:
  - build
  - test

before_script:
  # Cache-Verzeichnis definieren
  - flutter config --enable-web
  - flutter pub get

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .pub-cache/
    - build/

build:
  stage: build
  script:
    - flutter build web --web-renderer canvaskit --release --no-tree-shake-icons
  artifacts:
    paths:
     - build/web/

test:
  stage: test
  before_script:
    - apt-get install -y lcov
  script:
    - flutter test --coverage
  after_script:
    - genhtml coverage/lcov.info -o coverage/html
  artifacts:
    paths:
      - coverage/html/
    reports:
      junit: coverage/html/index.html