image: ghcr.io/cirruslabs/flutter:3.24.1

stages:
  - build
  - test
  - coverage

before_script:
  # Cache-Verzeichnis definieren
  - flutter config --enable-web
  - flutter pub get

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .pub-cache/
    - build/

build:
  stage: build
  script:
    - flutter build web --web-renderer canvaskit --release --no-tree-shake-icons
  rules:
    - when: always
  artifacts:
    paths:
     - build/web/

test:
  stage: test
  script:
    - flutter test --coverage
  rules:
    - when: always
  artifacts:
    paths:
      - coverage/lcov.info

coverage:
  stage: coverage
  before_script:
    - apt-get install -y lcov
  script:
    - lcov --capture --directory coverage --output-file coverage/lcov.info
    
    # Ermittle die geänderten Dateien im aktuellen Merge Request
    - |
      # Ersetze <SOURCE_BRANCH> und <TARGET_BRANCH> durch deine Branch-Namen
      SOURCE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      TARGET_BRANCH="main"  # oder der Basis-Branch des MRs

      # Get modified files
      modified_files=$(git diff --name-only origin/$TARGET_BRANCH...$SOURCE_BRANCH)

      # Filtere die lcov.info nur für die geänderten Dateien
      lcov --extract coverage/lcov.info "$modified_files" --output-file coverage/filtered_lcov.info

      # Generiere den HTML-Report
      genhtml coverage/filtered_lcov.info --output-directory coverage/html
      echo "Coverage for changed files generated."

      # Überprüfe die Coverage
      coverage_percent=$(lcov --list coverage/filtered_lcov.info | grep -oP "\d+\.\d+(?=%)" | head -n 1)
      echo "Coverage: $coverage_percent%"

      # Fails the pipeline if coverage is below 50%
      if (( $(echo "$coverage_percent < 50" | bc -l) )); then
        echo "Coverage is below 50%. Failing the pipeline."
        exit 1
      else
        echo "Coverage is acceptable."
      fi
  rules:
    - if: '$CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH != "main"'
      when: always
    - when: never
  artifacts:
    paths:
      - coverage/html/