name: finanzbegleiter
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_framework: ^1.1.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  firebase_core: ^2.25.1
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  dartz: ^0.10.1
  uuid: ^4.3.3
  url_strategy: ^0.2.0
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  flutter_modular: ^6.0.4+1
  firebase_storage: ^11.6.9
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_dropzone: ^3.0.7
  bloc_concurrency: ^0.2.5
  easy_image_viewer: ^1.4.1
  mockito: ^5.4.4
  build_runner: ^2.4.9
  collection: ^1.18.0
  flutter_staggered_animations: ^1.1.1
  firebase_auth_mocks: ^0.13.0
  cloud_functions: ^4.6.8
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  
  # Change assets/images to assets/assets/images for release build
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic


