name: finanzbegleiter
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_framework: ^1.1.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  firebase_core: ">=3.6.0 <5.0.0"
  firebase_auth: ">=5.3.1 <7.0.0"
  firebase_app_check: ">=0.3.1+4 <0.5.0"
  cloud_firestore: ">=5.4.4 <7.0.0"
  dartz: ^0.10.1
  uuid: ^4.3.3
  url_strategy: ^0.3.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  flutter_modular: ^6.0.4+1
  firebase_storage: ">=12.3.4 <14.0.0"
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_dropzone: ^4.0.3
  bloc_concurrency: ^0.3.0
  easy_image_viewer: ^1.4.1
  mockito: ^5.4.4
  build_runner: ^2.4.9
  collection: ^1.18.0
  flutter_staggered_animations: ^1.1.1
  cloud_functions: ">=5.1.3 <7.0.0"
  http: ^1.2.0
  emoji_picker_flutter: ^4.3.0
  url_launcher: ^6.0.20
  flex_color_picker: ^3.6.0
  rxdart: ^0.28.0
  flutter_iconpicker: ^4.0.1
  web: ^1.1.1
  sentry_flutter: ^9.0.0
  fl_chart: ^1.0.0
  flutter_image_compress: ^2.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ">=5.0.0 <7.0.0"

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  
  # Change assets/images to assets/assets/images for release build
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/ttf/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/ttf/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/ttf/Poppins/Poppins-Italic.ttf
          style: italic
    - family: Merriweather
      fonts:
        - asset: assets/fonts/ttf/Merriweather/Merriweather-Regular.ttf
        - asset: assets/fonts/ttf/Merriweather/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/ttf/Merriweather/Merriweather-Italic.ttf
          style: italic
        - asset: assets/fonts/ttf/Merriweather/Merriweather-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/ttf/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/ttf/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/ttf/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/ttf/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic


